version: '4'

services:
  database_ignite_tests:
    image: postgres
    container_name: database_ignite_tests
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx_tests
    ports:
      - 3333:3333
    volumes: 
    - .:/usr/app 
    depends_on:
      - database_ignite_tests
    links:
      - database_ignite_tests
volumes:
  pgdata:
    driver: local