version: '4'

services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 65432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=C{k0+30>>PlQOzRi
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx_tests
    ports:
      - 3333:3333
    volumes: 
    - .:/usr/app 
    depends_on:
      - database
    links:
      - database
volumes:
  pgdata:
    driver: local